# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_report_google_analytics_index:
    pattern: /report/google-analytics/index
    defaults: { _controller: CampaignChainReportGoogleAnalyticsBundle:GoogleAnalytics:index }

campaignchain_report_google_analytics_report:
    pattern: /report/google-analytics/report/{locationId}/{campaignId}
    defaults: { _controller: CampaignChainReportGoogleAnalyticsBundle:GoogleAnalytics:report }


