# This file is part of the CampaignChain package.
#
# (c) CampaignChain, Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    campaignchain_report_google_analytics.service_client:
        class: CampaignChain\Report\GoogleAnalyticsBundle\Service\AnalyticsApiClient
        arguments: [@campaignchain.core.location, @campaignchain.security.authentication.client.oauth.application, @campaignchain.security.authentication.client.oauth.token]
